/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package login;
import com.mysql.cj.protocol.Message;
import static database.Database.com;
import static database.Database.stm;
import javax.swing.*;
import java.awt.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.security.MessageDigest;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.*;
/**
 *
 * @author ASUS
 */
public class resgister extends javax.swing.JFrame {
     public static Connection com;
     public static Statement stm;
     

    /**
     * Creates new form resgister
     */
    public resgister() {
        initComponents();
        ndelik.setVisible(false);
        
         sign_in.addMouseListener(new MouseAdapter() {
        @Override
        public void mouseClicked(MouseEvent e) {
            // Membuka JFrame Login
            awal varel = new awal();
            varel.setVisible(true);
            dispose();
                }});
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mini = new javax.swing.JLabel();
        sign_in = new javax.swing.JButton();
        register = new javax.swing.JButton();
        show = new javax.swing.JLabel();
        ndelik = new javax.swing.JLabel();
        pw = new javax.swing.JPasswordField();
        username = new javax.swing.JTextField();
        metu = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mini.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/mini.png"))); // NOI18N
        mini.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                miniMouseClicked(evt);
            }
        });
        getContentPane().add(mini, new org.netbeans.lib.awtextra.AbsoluteConstraints(1340, 10, -1, -1));

        sign_in.setBorderPainted(false);
        sign_in.setContentAreaFilled(false);
        sign_in.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sign_inActionPerformed(evt);
            }
        });
        getContentPane().add(sign_in, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 250, 170, 40));

        register.setBorderPainted(false);
        register.setContentAreaFilled(false);
        register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerActionPerformed(evt);
            }
        });
        getContentPane().add(register, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 510, 440, 50));

        show.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/eye.png"))); // NOI18N
        show.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showMouseClicked(evt);
            }
        });
        getContentPane().add(show, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 420, -1, -1));

        ndelik.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/hide.png"))); // NOI18N
        ndelik.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ndelikMouseClicked(evt);
            }
        });
        getContentPane().add(ndelik, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 420, -1, -1));

        pw.setBackground(new java.awt.Color(58, 131, 188));
        pw.setForeground(new java.awt.Color(255, 255, 255));
        pw.setBorder(null);
        pw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwActionPerformed(evt);
            }
        });
        getContentPane().add(pw, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 410, 350, 30));

        username.setBackground(new java.awt.Color(58, 131, 188));
        username.setForeground(new java.awt.Color(255, 255, 255));
        username.setBorder(null);
        getContentPane().add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 330, 360, 30));

        metu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/X.png"))); // NOI18N
        metu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                metuMouseClicked(evt);
            }
        });
        getContentPane().add(metu, new org.netbeans.lib.awtextra.AbsoluteConstraints(1380, 10, 40, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Desktop - 7.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1440, 810));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void metuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_metuMouseClicked
       dispose();
    }//GEN-LAST:event_metuMouseClicked

    private void pwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pwActionPerformed

    private void showMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showMouseClicked
        show.setVisible(false);
      ndelik.setVisible(true);
      pw.setEchoChar((char)0);
    }//GEN-LAST:event_showMouseClicked

    private void ndelikMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ndelikMouseClicked
        show.setVisible(true);
      ndelik.setVisible(false);
      pw.setEchoChar('•');
    }//GEN-LAST:event_ndelikMouseClicked

    private void miniMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_miniMouseClicked
        this.setState(1);
    }//GEN-LAST:event_miniMouseClicked

    private void registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerActionPerformed
       String nama,password,query;
       String url,user,pass;
       url="jdbc:mysql://localhost:3306/loket_tiket";
       user="root";
       pass="";
       try{
           Class.forName("com.mysql.cj.jdbc.Driver");
            com =DriverManager.getConnection(url,user,pass);
            stm =com.createStatement();
            if("".equals(username.getText())){
                JOptionPane.showMessageDialog(new JFrame(), "Username diperlukan", "Error", JOptionPane.ERROR_MESSAGE);
            }else if("".equals(pw.getText())){
                JOptionPane.showMessageDialog(new JFrame(), "Password diperlukan", "Error", JOptionPane.ERROR_MESSAGE);
            }else{
                nama=username.getText();
                password=passhash(pw.getText());
                System.out.println(password);
                
                query="INSERT INTO login(username ,password)"+"VALUES('"+nama+"', '"+password+"')";
                
                stm.execute(query);
                username.setText("");
                pw.setText("");
                JOptionPane.showMessageDialog(null, "Akub Berhasil Dibuat");
                
                  awal awalFrame=new awal();
                    awalFrame.setVisible(true);
                    awalFrame.pack();
                    awalFrame.setLocationRelativeTo(null);
                    this.dispose();;
            }
       }catch(ClassNotFoundException | SQLException e){
           System.out.println("error"+e.getMessage());
       }
    }//GEN-LAST:event_registerActionPerformed

    public static String passhash(String password){
        try {
            MessageDigest md=MessageDigest.getInstance("SHA");
            md.update(password.getBytes());
            byte[] rbt=md.digest();
            StringBuilder sb=new StringBuilder();
            for(byte b:rbt){
                sb.append(String.format("%02x", b));
            }
            return sb.toString();
        } catch (Exception e) {
        }
         return null;
    }
    
    private void sign_inActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sign_inActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sign_inActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(resgister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(resgister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(resgister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(resgister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new resgister().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel metu;
    private javax.swing.JLabel mini;
    private javax.swing.JLabel ndelik;
    private javax.swing.JPasswordField pw;
    private javax.swing.JButton register;
    private javax.swing.JLabel show;
    private javax.swing.JButton sign_in;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
